flowchart TD
  E0[TransactionInitiated] --> E1[PaymentChannelValidated]
  E1[PaymentChannelValidated] --> E2[MerchantAuthenticated]
  E2[MerchantAuthenticated] --> E3[IdempotencyKeyAccepted]
  E3[IdempotencyKeyAccepted] --> E4[TransactionSchemaValidated]
  E4[TransactionSchemaValidated] --> E5[TransactionRejectedForSchema]
  E5[TransactionRejectedForSchema] --> E6[TransactionAccepted]
  E6[TransactionAccepted] --> E7[CustomerProfileRequested]
  E7[CustomerProfileRequested] --> E8[CustomerProfileLoaded]
  E8[CustomerProfileLoaded] --> E9[AccountStatusChecked]
  E9[AccountStatusChecked] --> E10[DeviceFingerprintMatched]
  E10[DeviceFingerprintMatched] --> E11[DeviceFingerprintNew]
  E11[DeviceFingerprintNew] --> E12[MerchantRiskLoaded]
  E12[MerchantRiskLoaded] --> E13[FeatureVectorBuilt]
  E13[FeatureVectorBuilt] --> E14[TransactionEnriched]
  E14[TransactionEnriched] --> E15[VelocityWindowUpdated]
  E15[VelocityWindowUpdated] --> E16[RuleSetLoaded]
  E16[RuleSetLoaded] --> E17[RuleEvaluated]
  E17[RuleEvaluated] --> E18[VelocityRuleMatched]
  E18[VelocityRuleMatched] --> E19[AmountRuleMatched]
  E19[AmountRuleMatched] --> E20[GeoRuleMatched]
  E20[GeoRuleMatched] --> E21[MccRuleMatched]
  E21[MccRuleMatched] --> E22[WatchlistRuleMatched]
  E22[WatchlistRuleMatched] --> E23[BehaviorRuleMatched]
  E23[BehaviorRuleMatched] --> E24[DeviceNetworkRuleMatched]
  E24[DeviceNetworkRuleMatched] --> E25[RuleEvaluationCompleted]
  E25[RuleEvaluationCompleted] --> E26[ModelVersionSelected]
  E26[ModelVersionSelected] --> E27[OnlineFeaturesFetched]
  E27[OnlineFeaturesFetched] --> E28[AnomalyModelInvoked]
  E28[AnomalyModelInvoked] --> E29[AnomalyScoreCalculated]
  E29[AnomalyScoreCalculated] --> E30[AnomalyScorePublished]
  E30[AnomalyScorePublished] --> E31[GraphNodeUpserted]
  E31[GraphNodeUpserted] --> E32[GraphEdgeUpserted]
  E32[GraphEdgeUpserted] --> E33[SharedDeviceDetected]
  E33[SharedDeviceDetected] --> E34[SharedIpDetected]
  E34[SharedIpDetected] --> E35[MuleClusterDetected]
  E35[MuleClusterDetected] --> E36[SuspiciousPathFound]
  E36[SuspiciousPathFound] --> E37[GraphSignalsPublished]
  E37[GraphSignalsPublished] --> E38[RiskSignalsCollected]
  E38[RiskSignalsCollected] --> E39[RiskScoreCalculated]
  E39[RiskScoreCalculated] --> E40[DecisionApproved]
  E40[DecisionApproved] --> E41[DecisionStepUpRequired]
  E41[DecisionStepUpRequired] --> E42[DecisionSentToReview]
  E42[DecisionSentToReview] --> E43[DecisionBlocked]
  E43[DecisionBlocked] --> E44[CaseCreated]
  E44[CaseCreated] --> E45[CaseAssigned]
  E45[CaseAssigned] --> E46[EvidenceAttached]
  E46[EvidenceAttached] --> E47[CustomerNotificationRequested]
  E47[CustomerNotificationRequested] --> E48[MerchantWebhookRequested]
  E48[MerchantWebhookRequested] --> E49[AnalystDecisionRecorded]
  E49[AnalystDecisionRecorded] --> E50[FalsePositiveCaptured]
  E50[FalsePositiveCaptured] --> E51[ConfirmedFraudCaptured]
  E51[ConfirmedFraudCaptured] --> E52[CardBlockRequested]
  E52[CardBlockRequested] --> E53[CardBlocked]
  E53[CardBlocked] --> E54[FundsHoldRequested]
  E54[FundsHoldRequested] --> E55[AuditRecordWritten]
  E55[AuditRecordWritten] --> E56[MetricsUpdated]
